[project]
name = "uds26-tree-count"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.2",
    "matplotlib>=3.10.8",
    "nbdime>=4.0.3",
]
